on:
    pull_request:
    workflow_dispatch: 
    push:
        branches: [master]

name: "Autobuild"
permissions:
  contents: read
env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_MULTILEVEL_LOOKUP: true
jobs:
    bnt:
        name: build and test
        runs-on: ubuntu-latest
        steps:
        - name: Cache nuget packages
          id: nuget-cache
          uses: actions/cache@v4
          with:
            path: ${{ github.workspace }}/.nuget/packages
            key: ${{ runner.os }}-nuget-cache
        - name: Cache .NET installation
          id: dotnet-cache
          uses: actions/cache@v4
          with:
            path: /usr/share/dotnet
            key: ${{ runner.os }}-dotnet-cache
        - name: "Setup .NET 9.0.x"
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: |
              8.0.x
              9.0.x
        - uses: actions/checkout@v4
        - run: dotnet restore --locked-mode
        - run: dotnet build --no-restore
        - run: dotnet test --no-build